### ISSUE TITLE
spring-rest-todos not syncing between clients

### ISSUE THREAD

**Issue by demonfiddler** [spring-attic/spring-sync-samples#2]
Out of the box, the spring-rest-todo doesn't work at all. I had to fix a couple of NPEs in both client and server, following which the MainControllerTest unit test did actually run and pass (once I'd commented out the class-level @Ignore). I also got a bunch of package.json 404s which I had to suppress by adding data-rave-meta="bower.json" to the <html> tag of index.html. Oh - and the build doesn't work on Windows; I had to change the bower install invocation to read cmd /c bower install. Also, the CURL commands in the README.md don't work on Windows - you have to use double, not single, quotes to quote each parameter, and you have to \\" escape all the embedded double quote characters. Finally, in the CURL 'apply patch' example, the URL is incorrect (should be http://localhost:8080/sync/todos ?) but even with that change applied, the server cannot deserialise an array of patches, likewise for the 'generate patch' example ("JsonMappingException: Can not deserialize instance of todos.Todo out of START_ARRAY token").

Once these fixes had been applied (patch available on request), the application appears to run correctly in the browser, as do the CURL list/create/update/delete command line examples. Creates, updates and deletes all get reflected in the browser UI and processed correctly server-side. **However**, multiple instances of the application do not stay in sync and it is necessary to refresh the other instance page(s) in order to see the updated data (which proves that the updates are reaching the server and being applied correctly). I do not understand the DS algorithm implementation sufficiently well to see why sync is not working.

Does anyone recall multiple spring-rest-todo clients syncing correctly in the past, or has this example just never worked fully? I have yet to try the scores example.

**Comment by gregturn** [comment]
This project is not under active development.
